links:
  rails_tutorial: 
  home_page: https://www.railstutorial.org/ 
  help_page: https://www.railstutorial.org/help
  book_page: https://www.railstutorial.org/book
  about_page: https://www.learnenough.com/
  rails_page: https://rubyonrails.org/
